//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nesterJ.rc
//
#define ID_RESET                        3
#define IDI_NESTERICON                  100
#define IDI_ROM                         101
#define IDI_TWINFAM                     102
#define IDI_FDS                         103
#define IDR_MENU1                       104
#define IDR_MAIN_ACCEL                  105
#define IDD_OPTIONS_PREFERENCES         106
#define IDD_OPTIONS_GRAPHICS            107
#define IDD_OPTIONS_SOUND               108
#define IDD_OPTIONS_CONTROLLERS         109
#define IDD_OPTIONS_PATHS               110
#define IDD_DATACHBARCODE               111
#define IDD_NETPLAY_SERVER              112
#define IDD_NETPLAY_SERVER1             113
#define IDD_HELP_ABOUT                  114
#define IDD_NETPLAY_CLIENT              115
#define IDC_BLACKANDWHITE               1000
#define IDC_DOUBLESIZE                  1001
#define IDC_SHOWSPRITES                 1003
#define IDC_SHOWALLSCANLINES            1004
#define IDC_DRAWOVERSCAN                1006
#define IDC_SOUNDENABLE                 1008
#define IDC_FULLSCREENONLOAD            1008
#define IDC_FULLSCREENSCALING           1009
#define IDC_SAMPLERATE                  1014
#define IDC_CONTROLLER1_TYPE            1015
#define IDC_BUFFERLEN                   1015
#define IDC_RUNINBG                     1016
#define IDC_SPEEDTHROTTLE               1017
#define IDC_BUTTON_A                    1018
#define IDC_AUTOFRAMESKIP               1018
#define IDC_BUTTON_B                    1019
#define IDC_ASSOCIATE                   1019
#define IDC_BUTTON_SELECT               1020
#define IDC_SOUND_FILTER_LOWPASS        1020
#define IDC_BUTTON_START                1021
#define IDC_BUTTON_UP                   1022
#define IDC_BUTTON_DOWN                 1023
#define IDC_SOUND_FILTER_NONE           1023
#define IDC_BUTTON_LEFT                 1024
#define IDC_SOUND_FILTER_LOWPASS_WEIGHTED 1024
#define IDC_BUTTON_RIGHT                1025
#define IDC_PRIORITY                    1025
#define IDC_TINT                        1026
#define IDC_HUE                         1027
#define IDC_UNDO                        1029
#define IDC_DEVICE                      1031
#define IDC_MODE                        1032
#define IDC_STATIC_UP                   1041
#define IDC_STATIC_DOWN                 1042
#define IDC_STATIC_LEFT                 1043
#define IDC_STATIC_RIGHT                1044
#define IDC_STATIC_SELECT               1045
#define IDC_STATIC_START                1046
#define IDC_STATIC_B                    1047
#define IDC_STATIC_A                    1048
#define IDC_UP_DEVICE                   1049
#define IDC_UP_BUTTON                   1050
#define IDC_SELECT_DEVICE               1051
#define IDC_DOWN_DEVICE                 1052
#define IDC_DOWN_BUTTON                 1053
#define IDC_LEFT_DEVICE                 1054
#define IDC_LEFT_BUTTON                 1055
#define IDC_RIGHT_DEVICE                1056
#define IDC_RIGHT_BUTTON                1057
#define IDC_SELECT_BUTTON               1058
#define IDC_START_DEVICE                1059
#define IDC_START_BUTTON                1060
#define IDC_B_DEVICE                    1061
#define IDC_B_BUTTON                    1062
#define IDC_A_DEVICE                    1063
#define IDC_A_BUTTON                    1064
#define IDC_PLAYER                      1065
#define IDC_DEFAULTS                    1066
#define IDC_CONTROLPANEL                1067
#define IDC_VERSION                     1071
#define IDC_RECTANGLE1                  1073
#define IDC_RECTANGLE2                  1074
#define IDC_TITLE                       1074
#define IDC_TRIANGLE                    1075
#define IDC_SLIDER1                     1075
#define IDC_FASTFPS                     1075
#define IDC_BARCODEVALUE                1075
#define IDC_NOISE                       1076
#define IDC_FASTFPSVALUE                1076
#define IDC_DPCM                        1077
#define IDC_SRAMPATH                    1077
#define IDC_USE_SRAMPATH                1078
#define IDC_USE_STATEPATH               1080
#define IDC_STATEPATH                   1081
#define IDC_USE_WAVEPATH                1083
#define IDC_WAVEPATH                    1084
#define IDC_TOGGLEFAST                  1089
#define IDC_USESTRETCHBLT               1090
#define IDC_EMULATETV                   1091
#define IDC_IPADDRESS                   1091
#define IDC_SKIPSOMEERRORS              1092
#define IDC_IPPORT                      1092
#define IDC_NETLATENCY                  1093
#define IDC_EXT                         1094
#define IDC_REF_SRAMPATH                1095
#define IDC_REF_STATEPATH               1096
#define IDC_REF_WAVEPATH                1097
#define IDC_LABEL_WAVE                  1098
#define IDC_LABEL_STATE                 1099
#define IDC_LABEL_SRAM                  1100
#define IDC_DEFAULTPALETTE              1101
#define IDC_READPALETTEFILE             1102
#define IDC_CALCPALETTE                 1103
#define IDC_PALETTEFILE                 1105
#define IDC_REF_PALETTEFILE             1106
#define IDC_LABEL_TINT                  1107
#define IDC_LABEL_HUE                   1108
#define IDC_LABEL_SHOT                  1109
#define IDC_USE_SHOTPATH                1110
#define IDC_SHOTPATH                    1111
#define IDC_REF_SHOTPATH                1112
#define IDC_SAMPLEBITS                  1114
#define IDC_IDEALTRIANGLE               1115
#define ID_FILE_OPEN_ROM                40001
#define ID_FILE_CLOSE_ROM               40002
#define ID_FILE_RESET                   40003
#define ID_FILE_SCREENSHOT              40004
#define ID_FILE_SNDREC                  40005
#define ID_FILE_MOVIE_PLAY              40006
#define ID_FILE_MOVIE_REC               40007
#define ID_FILE_MOVIE_STOP              40008
#define ID_FILE_NETPLAY_ACCEPT          40009
#define ID_FILE_NETPLAY_CONNECT         40010
#define ID_FILE_NETPLAY_CANCEL          40011
#define ID_FILE_NETPLAY_CLOSE           40012
#define ID_FILE_DISK_EJECT              40013
#define ID_FILE_DISK_1A                 40014
#define ID_FILE_DISK_1B                 40015
#define ID_FILE_DISK_2A                 40016
#define ID_FILE_DISK_2B                 40017
#define ID_FILE_SAVE_STATE              40018
#define ID_FILE_LOAD_STATE              40019
#define ID_FILE_QUICK_SAVE              40020
#define ID_FILE_QUICK_LOAD              40021
#define ID_FILE_SLOT_0                  40022
#define ID_FILE_SLOT_1                  40023
#define ID_FILE_SLOT_2                  40024
#define ID_FILE_SLOT_3                  40025
#define ID_FILE_SLOT_4                  40026
#define ID_FILE_SLOT_5                  40027
#define ID_FILE_SLOT_6                  40028
#define ID_FILE_SLOT_7                  40029
#define ID_FILE_SLOT_8                  40030
#define ID_FILE_SLOT_9                  40031
#define ID_FILE_RECENT_0                40032
#define ID_FILE_RECENT_1                40033
#define ID_FILE_RECENT_2                40034
#define ID_FILE_RECENT_3                40035
#define ID_FILE_RECENT_4                40036
#define ID_FILE_RECENT_5                40037
#define ID_FILE_RECENT_6                40038
#define ID_FILE_RECENT_7                40039
#define ID_FILE_RECENT_8                40040
#define ID_FILE_RECENT_9                40041
#define ID_FILE_EXIT                    40042
#define ID_OPTIONS_PREFERENCES          40043
#define ID_OPTIONS_GRAPHICS             40044
#define ID_OPTIONS_SOUND                40045
#define ID_OPTIONS_CONTROLLERS          40046
#define ID_OPTIONS_PATHS                40047
#define ID_OPTIONS_EXCONTROLLER_00      40048
#define ID_OPTIONS_EXCONTROLLER_02      40049
#define ID_OPTIONS_EXCONTROLLER_03      40050
#define ID_OPTIONS_EXCONTROLLER_04      40051
#define ID_OPTIONS_EXCONTROLLER_05      40052
#define ID_OPTIONS_EXCONTROLLER_06      40053
#define ID_OPTIONS_EXCONTROLLER_07      40054
#define ID_OPTIONS_EXCONTROLLER_08      40055
#define ID_OPTIONS_EXCONTROLLER_09      40056
#define ID_OPTIONS_EXCONTROLLER_10      40057
#define ID_OPTIONS_EXCONTROLLER_11      40058
#define ID_OPTIONS_EXCONTROLLER_12      40059
#define ID_OPTIONS_EXCONTROLLER_13      40060
#define ID_OPTIONS_EXCONTROLLER_14      40061
#define ID_OPTIONS_EXCONTROLLER_15      40062
#define ID_OPTIONS_EXCONTROLLER_16      40063
#define ID_OPTIONS_EXCONTROLLER_17      40064
#define ID_OPTIONS_EXCONTROLLER_18      40065
#define ID_OPTIONS_EXCONTROLLER_19      40066
#define ID_OPTIONS_BARCODE_INPUT        40067
#define ID_OPTIONS_TAPE_PLAY            40068
#define ID_OPTIONS_TAPE_REC             40069
#define ID_OPTIONS_TAPE_STOP            40070
#define ID_OPTIONS_DOUBLESIZE           40071
#define ID_OPTIONS_FULLSCREEN           40072
#define ID_HELP_ABOUT                   40073
#define ID_KEY_DISABLE                  40074
#define ID_OPTIONS_EXCONTROLLER_20      40075
#define ID_FILE_SOFTRESET               40076

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40077
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
