#ifndef HOSTSIM_INCLUDE_H_
#define HOSTSIM_INCLUDE_H_

#include <windows.h>
/*------------------------------------------------------------
	module:			Hostsim.h,Hostsim.cpp,Hostsim.dll
	date:			2004.10.28
	Version:		1.0.0
	Author:			yearn
	Description:	Processor part simulator support
	Revision:       1.1.0  Parallel port debug support
	                1.1.1  Use CRITICAL_SECTION to synchronize
					1.1.2  GetClkTick/SetClkTick ((clock tick low 32 bits))
					1.1.3  Split ppsim.h into two files,Remove MFC
					1.1.4  Epp support, Change name from ppsim to hostsim
					       Add Command_RTI function to hostsim socket.
						   GetClkTickH/SetClkTickH (clock tick high 32 bits)
					1.1.5  EnableIsr / DisableIsr
					       Suspend main thread while isr is executing.

	!!!DO NOT EDIT THIS FILE!!!
------------------------------------------------------------*/
#define	HOSTSIM_SUPPORT

#ifndef NULL
#define NULL  0
#endif

#ifndef BOOL
#define BOOL  int
#endif

#ifndef DWORD
#define DWORD unsigned long
#endif

typedef void  (*HostSim_VoidVoid)(void);
typedef BOOL  (*HostSim_WriteRegister)(int, int);
typedef BOOL  (*HostSim_ReadRegister)(int, int*);
typedef DWORD (*HostSim_GetClkTick)();
typedef void  (*HostSim_SetClkTick)(DWORD);
typedef void  (*HostSim_LPTWrite)(int,int);
typedef int   (*HostSim_LPTRead)(int);

typedef void  (*HostSim_ISR_Routine)(int);
typedef void  (*HostSim_ShowMsg)(char*);
typedef BOOL  (*HostSim_Init)(int,int,HostSim_ISR_Routine,HostSim_ShowMsg);

/********************************************************************/
/*                      User Invoked                                */
/********************************************************************/
extern  HostSim_WriteRegister BasicWriteReg8;
extern  HostSim_ReadRegister  BasicReadReg8;
extern  HostSim_GetClkTick    GetClkTick;
extern  HostSim_SetClkTick    SetClkTick;
extern  HostSim_VoidVoid	  Trap;
extern  HostSim_VoidVoid      Command_RTI;
extern  HostSim_VoidVoid      EnableIsr;
extern  HostSim_VoidVoid      DisableIsr;
extern  BOOL                  InitHostSim(int,int,HostSim_ISR_Routine,HostSim_ShowMsg);
extern  void                  ReleaseHostSim();
//extended hostsim
extern  HostSim_GetClkTick    GetClkTickH;
extern  HostSim_SetClkTick    SetClkTickH;
extern  HostSim_WriteRegister BasicWriteReg32;
extern  HostSim_ReadRegister  BasicReadReg32;
extern  HostSim_LPTWrite      LPTWrite;
extern  HostSim_LPTRead       LPTRead;
//compatible name defines for older ppsim version
#define BasicWriteReg		  BasicWriteReg8
#define BasicReadReg		  BasicReadReg8
#define InitPPSim             InitHostSim
#define ReleasePPSim          ReleaseHostSim
/*---------------------------------------------------*/
#endif
