AS=sparc-rtems-as
CC=sparc-rtems-gcc
DUMP=sparc-rtems-objdump

CFLAGS = -g -c -O2 -mv8 -mno-fpu -DLEON -Dkillsystem -DDTCM8K
#CFLAGS = -g -c -O2 -mv8 -mno-fpu -DLEON -Dkillsystem -DDTCM8K -DTESTGRAPH
#CFLAGS = -g -c -O2 -mv8 -mno-fpu -DLEON --verbose
#ASFLAGS = -D -gstabs 
LDFLAGS = -g -N -Ttext=40000000 #-nostdlib -nodefaultlibs -nostdinclude #-e main 
LIBS= -LD:/cygwin/opt/rtems/sparc-rtems/lib -lgcc
DUMPFLAGS = -a -f -x -d -S -s -t

OBJS = K6502.o InfoNES_pAPU.o InfoNES.o mario.o leonram.o AVSync.o Int.o periph.o
#OBJS = K6502.o InfoNES_pAPU.o InfoNES.o mario.o leonram.o
#OBJS = K6502.o InfoNES_pAPU.o InfoNES.o
#OBJS = InfoNES_System_LEON.o K6502.o InfoNES_pAPU.o InfoNES.o

all: $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o InfoNES.elf

sd: all
	${DUMP} ${DUMPFLAGS} InfoNES.elf > InfoNES.sd
	sparc-rtems-size InfoNES.elf

bin: all
	sparc-rtems-objcopy -O binary InfoNES.elf InfoNES.bin
	sparc-rtems-size InfoNES.elf

rebuild: clean all

clean:
	rm -f *.o
	rm -f *.elf
	rm -f *.sd
	rm -f *.bin
	
K6502.o: ../K6502.cpp ../K6502.h ../InfoNES_Types.h ../InfoNES.h ../K6502_rw.h ../InfoNES_pAPU.h
	$(CC) -c $(CFLAGS) ../K6502.cpp -o K6502.o

InfoNES_pAPU.o: ../InfoNES_pAPU.cpp ../K6502.h ../K6502_rw.h ../InfoNES.h ../InfoNES_Types.h ../InfoNES_pAPU.h
	$(CC) -c $(CFLAGS) ../InfoNES_pAPU.cpp -o InfoNES_pAPU.o

InfoNES.o: ../InfoNES.cpp ../InfoNES.h ../InfoNES_Types.h ../InfoNES_pAPU.h ../K6502.h
	$(CC) -c $(CFLAGS) ../InfoNES.cpp -o InfoNES.o

mario.o: ../gamefile/mario.cpp
	$(CC) -c $(CFLAGS) ../gamefile/mario.cpp -o mario.o

leonram.o: ../leonram.cpp
	$(CC) -c $(CFLAGS) ../leonram.cpp -o leonram.o

AVSync.o: ../AVSync.cpp ../AVSync.h
	$(CC) -c $(CFLAGS) ../AVSync.cpp -o AVSync.o

Int.o: ../Int.cpp ../Int.h
	$(CC) -c $(CFLAGS) ../Int.cpp -o Int.o

periph.o: ../periph.cpp ../periph.h
	$(CC) -c $(CFLAGS) ../periph.cpp -o periph.o

                                                                                                        